/**
 * Neynar helpers for Farcaster server-side posting.
 *
 * Flow (Managed Signers):
 *   1. Client requests a new signer for their TON wallet address.
 *   2. Server calls Neynar to create a signer (public key generated by
 *      Neynar; private key held by Neynar so we never touch it).
 *   3. Neynar returns a `signer_approval_url` that opens Warpcast in
 *      the user's browser. The user taps Approve, which delegates
 *      "cast on my behalf" permission to our signer.
 *   4. Client polls signer status until `approved`.
 *   5. From then on, we call POST /v2/farcaster/cast with the
 *      signer_uuid + text + embeds to publish casts as that user.
 *
 * The signer is persisted per-wallet in Vercel KV so users only
 * connect once.
 */

import { getRedis } from './trustStore'

const NEYNAR_BASE = 'https://api.neynar.com/v2/farcaster'

function apiKey(): string {
  const k = process.env.NEYNAR_API_KEY
  if (!k) throw new Error('NEYNAR_API_KEY env not configured')
  return k
}

function headers(): Record<string, string> {
  return {
    'accept': 'application/json',
    'content-type': 'application/json',
    'x-api-key': apiKey(),
  }
}

export interface NeynarSignerRecord {
  signer_uuid: string
  public_key: string
  status: 'generated' | 'pending_approval' | 'approved' | 'revoked'
  signer_approval_url?: string
  fid?: number
  createdAt: number
}

const kv = () => getRedis()
const signerKey = (wallet: string) => `fc:signer:${wallet.toLowerCase()}`

export async function loadSigner(wallet: string): Promise<NeynarSignerRecord | null> {
  return (await kv().get<NeynarSignerRecord>(signerKey(wallet))) ?? null
}

export async function saveSigner(wallet: string, rec: NeynarSignerRecord): Promise<void> {
  await kv().set(signerKey(wallet), rec)
}

export async function clearSigner(wallet: string): Promise<void> {
  await kv().del(signerKey(wallet))
}

/**
 * Create a fresh signer + register it with Farcaster, returning the
 * approval URL the user needs to open in Warpcast.
 */
export async function createAndRegisterSigner(): Promise<{
  signer_uuid: string
  public_key: string
  signer_approval_url: string
  status: 'pending_approval' | 'generated'
}> {
  // 1) Create the signer key pair on Neynar
  const createRes = await fetch(`${NEYNAR_BASE}/signer`, {
    method: 'POST',
    headers: headers(),
  })
  if (!createRes.ok) {
    const t = await createRes.text().catch(() => '')
    throw new Error(`Neynar signer create failed (${createRes.status}): ${t.slice(0, 200)}`)
  }
  const created = await createRes.json() as {
    signer_uuid: string
    public_key: string
    status: string
  }

  // 2) Register the signed key with the sponsor (Neynar as sponsor) so
  //    that the approval URL can be issued. Neynar's `registered_signer`
  //    endpoint returns the sponsored approval URL directly.
  const regRes = await fetch(`${NEYNAR_BASE}/signer/signed_key`, {
    method: 'POST',
    headers: headers(),
    body: JSON.stringify({
      signer_uuid: created.signer_uuid,
      sponsor: true,
    }),
  })
  if (!regRes.ok) {
    const t = await regRes.text().catch(() => '')
    throw new Error(`Neynar signer signed_key failed (${regRes.status}): ${t.slice(0, 200)}`)
  }
  const registered = await regRes.json() as {
    signer_uuid: string
    public_key: string
    status: string
    signer_approval_url: string
  }

  return {
    signer_uuid: registered.signer_uuid,
    public_key: registered.public_key,
    signer_approval_url: registered.signer_approval_url,
    status: (registered.status as 'pending_approval' | 'generated') ?? 'pending_approval',
  }
}

/**
 * Poll signer status. When the user taps Approve in Warpcast, the
 * status flips from `pending_approval` → `approved` and the response
 * carries their Farcaster user id (`fid`).
 */
export async function fetchSignerStatus(signer_uuid: string): Promise<{
  status: 'generated' | 'pending_approval' | 'approved' | 'revoked'
  fid?: number
  public_key?: string
}> {
  const res = await fetch(`${NEYNAR_BASE}/signer?signer_uuid=${encodeURIComponent(signer_uuid)}`, {
    headers: headers(),
  })
  if (!res.ok) {
    const t = await res.text().catch(() => '')
    throw new Error(`Neynar signer status failed (${res.status}): ${t.slice(0, 200)}`)
  }
  return await res.json() as {
    status: 'generated' | 'pending_approval' | 'approved' | 'revoked'
    fid?: number
    public_key?: string
  }
}

/**
 * Publish a cast on behalf of the user. `embeds` should be an array
 * of URL strings — Warpcast renders each as a rich embed card.
 */
export async function publishCast(args: {
  signer_uuid: string
  text: string
  embeds?: string[]
  channel_id?: string
}): Promise<{ hash: string; text: string }> {
  const body: Record<string, unknown> = {
    signer_uuid: args.signer_uuid,
    text: args.text,
  }
  if (args.embeds && args.embeds.length > 0) {
    body.embeds = args.embeds.map((u) => ({ url: u }))
  }
  if (args.channel_id) {
    body.channel_id = args.channel_id
  }
  const res = await fetch(`${NEYNAR_BASE}/cast`, {
    method: 'POST',
    headers: headers(),
    body: JSON.stringify(body),
  })
  if (!res.ok) {
    const t = await res.text().catch(() => '')
    throw new Error(`Neynar cast failed (${res.status}): ${t.slice(0, 200)}`)
  }
  const j = await res.json() as { cast?: { hash: string; text: string } }
  if (!j.cast) throw new Error('Neynar cast returned no cast object')
  return { hash: j.cast.hash, text: j.cast.text }
}
